config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  scope "/blog" do
    get "/login", to: "sessions#new"
    get "/logout", to: "sessions#destroy"
    get "/register", to: "users#new"
    get "/my", to: "users#index"
    get "/my/articles", to: "users#articles"

    resources :articles, only: [:index, :show, :new, :create, :edit]
    resources :users, only: [:new, :create, :index, :show]
    resources :sessions, only: [:new, :create, :destroy]
  end

  scope "/game" do
    get "/buddy", to: "buddy#show"
    get "/buddy/all", to: "buddy#index"
    post "/buddy", to: "buddy#create"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {maximum: 256}
  validates :body, presence: true, length: {maximum: 4096}
  validates :cover_url, format: {with: URI::regexp(%w(http https)), message: "must be a valid URL"}, allow_blank: true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  validates :content, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_save :downcase_email, :set_default_name

  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 8}, allow_nil: false
  validates :bio, length: {maximum: 128}
  validates :name, length: {maximum: 32}

  has_many :articles, dependent: :destroy

  def downcase_email
    email.downcase!
  end

  def set_default_name
    self.name = username if name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_user

  def is_logged_in?
    return !!session[:user_id]
  end

  def require_login
    if !is_logged_in?
      redirect_to new_session_path, notice: "You must be logged in to do that."
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id
    if @article.save
      redirect_to @article
    else
      flash[:error] = "Oops! Something went wrong. Please try again."
      redirect_to new_article_path
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])

    if @article.author_id != current_user.id
      redirect_to @article, notice: "You do not have permission to edit this article."
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :cover_url, :tags => [])
  end
end

app/controllers/buddy_controller.rb
class BuddyController < ApplicationController
  def show
    @buddies = Buddy.all
  end

  def new
    @buddy = Buddy.new
  end

  def index
    @buddies = Buddy.all
    render json: @buddies
  end

  def create
    @buddy = Buddy.new(buddy_params)
    @buddy.save
    redirect_to buddy_path
  end

  private
  def buddy_params
    params.permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    if is_logged_in?
      @current_user = current_user
    end

    @articles = Article.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def create
    session_params = params.permit(:username, :password)
    @user = User.find_by(username: session_params[:username])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to my_path
    else
      redirect_to login_path, notice: "Please ensure that you have entered the correct username and password."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def show
    @user = User.find(params[:id])
    @articles = Article.where(author_id: params[:id])
  end

  def index
    @current_user = current_user
  end

  def new
    @user = User.new
  end

  def create
    if User.find_by(username: params[:user][:username])
      redirect_to new_user_path, notice: "Username is already taken."
    elsif User.find_by(email: params[:user][:email])
      redirect_to new_user_path, notice: "Email is already taken."
    else
      @user = User.new(user_params)
      if @user.valid?
        session[:user_id] = @user.id
        @user.save
        redirect_to @user
      else
        redirect_to register_path, notice: "Oops! Something went wrong. Please try again later."
      end
    end
  end

  def articles
    @articles = Article.where(author_id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :bio, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/buddy_helper.rb
module BuddyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/index.html.erb
<div class="flex flex-col gap-4 md:m-12">
  <h1 class="text-3xl font-krona text-bold">Articles</h1>
  <ul class="flex flex-col gap-2">
    <% @articles.each do |article| %>
      <li>
        <a href="/articles/<%= article.id %>">
          <i><%= article.title %></i>
          <span class="text-gray-400">
           (By <%= User.find(article.author_id).name %>)
          </span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" src = "../../assets/froala_editor.pkgd.min.js"></script>

app/views/articles/new.html.erb
<div class="grid lg:w-[97vw] lg:grid-cols-2 grid-cols-1 place-items-center gap-1 my-12">
  <div class="flex flex-col w-full justify-center items-center">
    <%= form_with class: "flex flex-col gap-2 justify-center lg:max-w-lg w-full", model: @article, url: articles_path, method: :post do |form| %>
      <%= form.text_field :title, class: "input input-bordered w-full", id: "title", required: true, placeholder: "Title *" %><br>
      <%= form.text_field :cover_url, class: "input input-bordered w-full", id: "cover", required: true, placeholder: "Cover URL" %><br>
      <%= form.text_area :body, class: "textarea textarea-bordered w-full", id: "content", required: true, placeholder: "Content *" %><br>
      <%= form.text_field :tags, class: "input input-bordered w-full", required: true, placeholder: "Tags * (Seperated with commas)" %>
      <%= form.submit "Create", class: "btn btn-primary w-full" %>
    <% end %>
  </div>
  <div class="h-full w-full p-12 flex flex-col gap-4 rounded-lg bg-base-300">
    <img
      src="https://placehold.co/500x500"
      alt="Article <%= @article.id %> cover image"
      class="w-full object-cover rounded-lg max-w-none"
      style="max-width: none; width: 100%; height: 200px;"
    >
    <h1 class="text-3xl font-bold font-kanit break-words" id="article-name">
      My New Article
    </h1>
    <p class="break-words" id="article-body">
      Lorem ipsum...
    </p>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/gh/jitbit/HtmlSanitizer@master/HtmlSanitizer.js"></script>
<script>
  HtmlSanitizer.AllowedTags['H1'] = true;
  HtmlSanitizer.AllowedTags['P'] = true;
  let cover = document.getElementById("cover");
  let title = document.getElementById("title");
  let content = document.getElementById("content");
  let articleName = document.getElementById("article-name");
  let articlePreview = document.getElementById("article-body");

  cover.addEventListener("input", () => {
    document.querySelector("img").src = cover.value;
  });

  title.addEventListener("input", () => {
    articleName.innerText = title.value;
  });

  content.addEventListener("input", () => {
    articlePreview.innerHTML = HtmlSanitizer.SanitizeHtml(content.value);
  });

  articleName.innerText = title.value;
  articlePreview.innerHTML = HtmlSanitizer.SanitizeHtml(content.value);
  document.querySelector("img").src = cover.value;
</script>
<script>
  const tx = document.getElementsByTagName("textarea");
  for (let i = 0; i < tx.length; i++) {
    tx[i].setAttribute("style", "height:" + (tx[i].scrollHeight) + "px;overflow-y:hidden;");
    tx[i].addEventListener("input", OnInput, false);
  }

  function OnInput() {
    this.style.height = 0;
    this.style.height = (this.scrollHeight) + "px";
  }
</script>

app/views/articles/show.html.erb
<%
  require 'digest'
  author = User.find(@article.author_id)
%>

<div class="flex h-screen justify-center my-24">
  <div class="flex flex-col gap-4 max-w-xl p-4 w-full items-center justify-center overflow-hidden">
    <img
      src="<%= @article.cover_url %>"
      alt="Article <%= @article.id %> cover image"
      class="w-full object-cover rounded-lg max-w-none"
      style="max-width: none; width: 100%; height: 300px;"
    >
    <h1 class="text-3xl font-bold font-kanit break-words">
      <%= @article.title %>
    </h1>

    <div
      class="flex flex-row items-center justify-center bg-base-300 p-2 rounded-lg gap-2 cursor-pointer"
      onclick="window.location.href = '<%= user_path(author) %>'"
    >
      <img
        src="<%= "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(author.email)}?s=50" %>"
        alt="Article <%= @article.id %> author avatar"
        class="w-8 h-8 rounded-full"
      >
      <div class="flex flex-col">
        <span class="text-base font-bold font-kanit">
          <%= author.name %>
        </span>
        <span class="text-xs text-gray-500 font-kanit">
          <%= @article.created_at.strftime("%B %d, %Y") %>
        </span>
      </div>
    </div>

    <p class="break-words">
      <%== @article.body %>
    </p>

  </div>
</div>

app/views/buddy/show.html.erb
<script src="https://pixijs.download/release/pixi.js"></script>

<div class="grid h-screen w-screen mx-auto bg-white">
  <div class="flex flex-col gap-1 items-center my-12 w-full">
      <%= form_with url: buddy_path, class: "flex flex-col gap-none w-full max-w-lg" do |form| %>
      <label class="label">
      <span class="label-text font-itim text-black text-xl">
        เขียนบอกบัดดี้กันเถอะ
      </span>
      </label>
      <%= form.text_field :content, class: "w-full bg-white border-4 rounded-lg border-black font-itim text-black", placeholder: "เพื่อนน๊อตชอบกินผู้ขาย..." %>
      <% end %>
  </div>
  <div id="canvasDiv"></div>
</div>

<script>
  let app = new PIXI.Application({ width: window.innerWidth, height: 400, background: "#FFFFFF" });
document.getElementById("canvasDiv").appendChild(app.view);

  fetch("/game/buddy/all")
    .then(response => response.json())
    .then(data => {
      const text = data.map(buddy => buddy.content);

      text.forEach((text, index) => {
        // Random rotation (5 deg), and font size
        const rotation = Math.random() * 0.1 - 0.05;
        const fontSize = Math.random() * 32 + 16;

        // Create a new Text object
        const textObject = new PIXI.Text(text, {
          fontFamily: "Itim",
          fontSize: fontSize,
          fill: "black",
          align: "center",
          wordWrap: true,
          wordWrapWidth: 440
        });

        // Set the text object's anchor point to the start of the text
        textObject.anchor.set(0, 0);

        // Set the text object's rotation
        textObject.rotation = rotation

        // Set the text object's position to a random point on the canvas
        textObject.x = Math.random() * (app.screen.width - textObject.width);
        textObject.y = Math.random() * (app.screen.height - textObject.height);

        // Make text not overlapping with each other
        for (let i = 0; i < index; i++) {
          const otherText = app.stage.children[i];
          const hit = hitTestRectangle(textObject, otherText);
          if (hit) {
            textObject.x = Math.random() * (app.screen.width - textObject.width);
            textObject.y = Math.random() * (app.screen.height - textObject.height);
            i = -1;
          }
        }

        function hitTestRectangle(r1, r2) {
          //Define the variables we'll need to calculate
          let hit, combinedHalfWidths, combinedHalfHeights, vx, vy;

          //hit will determine whether there's a collision
          hit = false;

          //Find the center points of each sprite
          r1.centerX = r1.x + r1.width / 2;
          r1.centerY = r1.y + r1.height / 2;
          r2.centerX = r2.x + r2.width / 2;
          r2.centerY = r2.y + r2.height / 2;

          //Find the half-widths and half-heights of each sprite
          r1.halfWidth = r1.width / 2;
          r1.halfHeight = r1.height / 2;
          r2.halfWidth = r2.width / 2;
          r2.halfHeight = r2.height / 2;

          //Calculate the distance vector between the sprites
          vx = r1.centerX - r2.centerX;
          vy = r1.centerY - r2.centerY;

          //Figure out the combined half-widths and half-heights
          combinedHalfWidths = r1.halfWidth + r2.halfWidth;
          combinedHalfHeights = r1.halfHeight + r2.halfHeight;

          //Check for a collision on the x axis
          if (Math.abs(vx) < combinedHalfWidths) {
            //A collision might be occuring. Check for a collision on the y axis
            if (Math.abs(vy) < combinedHalfHeights) {
              //There's definitely a collision happening
              hit = true;
            } else {
              //There's no collision on the y axis
              hit = false;
            }
          } else {
            //There's no collision on the x axis
            hit = false;
          }

          //`hit` will be either `true` or `false`
          return hit;
        }

        // Add the text object to the stage
        app.stage.addChild(textObject);
      });
    });
</script>

app/views/home/index.html.erb
<div class="flex min-h-screen mx-4 my-12">
  <div class="flex flex-col gap-6 w-full lg:mx-12">
    <div class="flex flex-col gap-2 items-center justify-center">
      <h1 class="font-krona text-5xl">
        BLOG SPACE
      </h1>
      <p class="font-kanit text-sm text-gray-400">
        A blog space for all your thoughts
      </p>
    </div>
    <div class="grid grid-cols-3 w-full gap-2">
      <% @articles.each do |article| %>
        <div
          class="card card-compact w-128 bg-base-300 shadow-xl cursor-pointer"
          onclick="window.location.href='<%= article_path(article) %>'"
        >
          <figure>
            <img src="<%= article.cover_url %>" alt="Article <%= article.id %> cover image" />
          </figure>
          <div class="card-body">
            <h2 class="card-title">
              <%= truncate article.title %>
            </h2>
            <p>
              <%= truncate article.body %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <a href=<%= articles_path %>>
      <button class="w-full px-4 py-2 btn btn-primary">
        View all articles
      </button>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog of Tinarskii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Itim&family=Kanit&family=Krona+One&family=Noto+Emoji&family=Sarabun&display=swap" rel="stylesheet">     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

  <!-- Navigation -->
  <div class="navbar bg-base-300">
    <div class="flex-1">
      <a class="btn btn-ghost normal-case text-2xl font-krona" href="/">
        TINARSKII
      </a>
    </div>
    <div class="flex-none">
      <p>
        <% if @current_user %>
          <a class="btn btn-ghost normal-case text-sm font-krona" href=<%= my_path %>>
            <%= t('my_account') %>
          </a>
        <% else %>
          <a class="btn btn-ghost normal-case text-sm font-krona" href=<%= login_path %>>Login</a>
        <% end %>
      </p>
    </div>
  </div>
  <%= yield %>
  <footer class="footer footer-center p-4 bg-base-300 text-base-content">
    <div>
      <p>
        Copyright &copy; 2022
        <span class="font-krona">
          TINARSKII
        </span>
        — All rights reserved
      </p>
    </div>
  </footer>
  </body>
</html>

app/views/users/articles.html.erb
My Articles
<% if @articles %>
  <% @articles.each do |article| %>
    <div class="article">
      <h2><%= link_to article.title, article_path(article) %></h2>
    </div>
  <% end %>
<% else %>
  <p>
    Hmm, it looks like you haven't written any articles yet.
  </p>
<% end %>

app/views/users/index.html.erb
<div class="flex flex-col gap-4 m-12">
  <h1 class="text-3xl font-krona">
    Welcome, <%= current_user.name %>
  </h1>
  <div class="flex w-full gap-2">
    <a href="/articles/new">
      <button class="btn btn-primary">
        Create new articles
      </button>
    </a>
    <a href="/logout">
      <button class="btn btn-error">
        Logout
      </button>
    </a>
  </div>
</div>

app/views/users/new.html.erb
<div class="grid h-screen place-items-center my-12 w-full">
  <%= form_with model:@user, url: users_path, :class => "flex flex-col gap-4 p-12 justify-center bg-base-300 rounded-xl shadow w-1/2" do |form| %>
    <div class="flex flex-col gap-1">
      <h1 class="text-4xl font-bold text-center">
        <%= t('account.signup') %>
      </h1>
      <p class="text-sm text-center text-gray-400">
        <%= t('account.have_account') %>
        <span class="underline text-blue-500">
          <%= link_to t('menu.login'), login_path %>
        </span>
      </p>
    </div>

    <div class="flex flex-row gap-2">
      <!-- Username -->
      <div class="flex flex-col gap-1 w-full">
        <label class="label">
        <span class="label-text">
          <%= t('account.enter_username') %>
        </span>
        </label>
        <%= form.text_field :username, :class => "input input-bordered w-full" %>
      </div>
      <!-- Profile name -->
      <div class="flex flex-col gap-1 w-full">
        <label class="label">
        <span class="label-text">
          <%= t('account.enter_name') %>
        </span>
        </label>
        <%= form.text_field :name, :class => "input input-bordered w-full" %>
      </div>
    </div>

    <!-- Email -->
    <div class="flex flex-col gap-1">
      <label class="label">
        <span class="label-text">
          <%= t('account.enter_email') %>
        </span>
      </label>
      <%= form.email_field :email, required: true, :class => "input input-bordered w-full" %>
    </div>

    <!-- Password -->
    <div class="flex flex-col gap-1">
      <label class="label">
        <span class="label-text">
          <%= t('account.enter_password') %>
        </span>
      </label>
      <%= form.password_field :password, required: true, :class => "textarea textarea-bordered" %>
    </div>

    <!-- Bio -->
    <div class="flex flex-col gap-1">
      <label class="label">
        <span class="label-text">
          <%= t('account.enter_bio') %>
        </span>
      </label>
      <%= form.text_area :bio, :class => "textarea textarea-bordered" %>
    </div>

    <%= link_to t('account.signup'), register_path, :class => "btn btn-primary w-full" %>
  <% end %>
</div>

app/views/users/show.html.erb
<p>
  This account belongs to <%= @user.name %>
</p>

<p>
  Their articles:
</p>

<% if @articles %>
  <% @articles.each do |article| %>
    <div class="article">
      <h2><%= link_to article.title, article_path(article) %></h2>
    </div>
  <% end %>
<% else %>
  <p>
    Hmm, it looks like you haven't written any articles yet.
  </p>
<% end %>